[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
macros = { path = "../macros" }
eframe = { version = "0.31.1", features = ["default"] }
egui_extras = { version = "0.31.1", features = ["svg", "image"] }
egui_dock = "0.16.0"
cgmath = "0.18.0"
ps2-filetypes = { path = "../ps2-filetypes" }
image = { version = "0.25.6" }
lazy_static = "1.5.0"
rfd = "0.15.3"
wavefront_obj = "11.0.0"
bytesize = "2.0.1"

[build-dependencies]
winresource = "0.1.20"
