[package]
name = "gui-core"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.1"
psu-packer = { path = "../psu-packer" }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
ps2-filetypes = { path = "../ps2-filetypes" }
tempfile = "3"
