[workspace]
resolver = "2"
members = [
    "crates/suitcase",
    "crates/ps2-filetypes",
    "crates/xtask-build-app",
    "crates/memcard",
    "crates/psu-packer",
    "crates/psu-packer-gui",
]
default-members = ["crates/psu-packer-gui"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
