[workspace]
resolver = "2"
members = ["crates/suitcase", "crates/macros","crates/ps2-filetypes", "crates/ps2-mcm", "crates/ps2-psupacker", "crates/xtask-build-app"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
