[workspace]
resolver = "2"
members = [ "crates/builder", "crates/macros","crates/ps2-filetypes", "crates/ps2-mcm", "crates/ps2-psupacker"]

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.81"
version = "0.1.0"