[package]
name = "psu-packer-gui"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
psu-packer = { path = "../psu-packer" }
eframe = "0.27"
rfd = "0.14"
chrono = "0.4.42"
toml_edit = "0.22"
