[package]
name = "ps2-filetypes"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.40"
image = "0.25.6"
indexmap = "2.10.0"
encoding_rs = "0.8"
toml = "0.9.2"

[dev-dependencies]
base64 = "0.22"
