[package]
name = "icon-sys-ui"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
egui = "0.31.1"
ps2-filetypes = { path = "../ps2-filetypes" }
psu-packer = { path = "../psu-packer" }
