name: Build PSU Packer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{matrix.os.name}}
    strategy:
      matrix:
        os:
          - name: ubuntu
            version: ubuntu-latest
            executable: psu-packer
          - name: macos
            version: macos-latest
            executable: psu-packer
          - name: windows
            version: windows-latest
            executable: psu-packer.exe
    runs-on: ${{matrix.os.version}}

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --package psu-packer --verbose --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: psu-packer-${{matrix.os.name}}
          path: target/release/${{matrix.os.executable}}